name: flutter drive

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*"

jobs:
  test:
    # Don't clutter up CI project with tests from other repos.
    if: startsWith(github.repository, 'futureware-tech/')
    strategy:
      fail-fast: false
      matrix:
        device:
          # Flutter only supports 64-bit simulators:
          # https://flutter.dev/docs/get-started/install/macos.
          - "iPhone 8"
          - "iPhone 11 Pro Max"
          - "iPad Pro (12.9-inch) (4th generation)"
    runs-on: macOS-latest
    steps:
      - uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.device }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: git fetch --tags
        working-directory: flutter/.flutter
      - name: "Install dependencies"
        run: |
          bundle install --deployment
          cd flutter
          bundle exec fastlane install_dependencies
          bundle exec fastlane install_ci_keys

      - name: "Build and run tests (default error reporting environment)"
        if: github.event_name == 'pull_request'
        working-directory: flutter
        run: >
          bundle exec fastlane run flutter
          args:drive,--target,test_driver/main.dart

      - name: "Build and run tests (ci error reporting environment)"
        if: github.event_name == 'push'
        working-directory: flutter
        run: >
          bundle exec fastlane run flutter
          args:drive,--target,test_driver/main.dart,--dart-define,sentry.environment=ci
