name: fastlane update

on:
  schedule:
    # Every day at 3:04 UTC: https://crontab.guru/#4_3_*_*_*
    - cron: "4 3 * * *"

jobs:
  fastlane-update:
    # Do not run on forks.
    if: github.repository_owner == 'futureware-tech'
    strategy:
      matrix:
        use_private_runner:
          - ${{ contains(fromJSON(
            '[
            "futureware-tech/delern",
            "futureware-tech/fw_ads"
            ]'), github.repository) }}
    runs-on: ${{
      matrix.use_private_runner &&
      fromJSON('["self-hosted", "macOS"]') ||
      'macOS-latest'
      }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # Required to fetch branches for submodules. Since we update flutter
          # in this workflow, we need to be able to fetch the branches, which
          # are otherwise pinned to just "master". See also:
          # https://github.community/t/128453
          fetch-depth: '0'
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - uses: ruby/setup-ruby@v1
        if: ${{ !matrix.use_private_runner }}
      - uses: subosito/flutter-action@v1
      - name: "Install dependencies"
        run: |
          gem environment
          gem install bundler --no-doc
          bundle install
          bundle console <<<RUBY_VERSION
      - name: "Install artifacts so that Flutter app can be built (for Pods)"
        working-directory: flutter
        run: bundle exec fastlane install_ci_keys
      - name: "Update fastlane"
        run: bundle update
      - name: "Update dependencies"
        run: bundle exec fastlane update
      - name: "Check for changes and create/update PR"
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.FASTLANE_UPDATE_GITHUB_TOKEN }}"
          commit-message: "[auto] update dependencies"
          branch: automated-update
          title: "[auto] update dependencies"
          labels: auto,dependencies
